version: '3.7'
services:

  mysql:
    image: mysql:8.1.0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: