version: '3.7'
services:

  mysql:
    image: mysql:8.1.0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_DATABASE:-QA_logs}
      - MYSQL_USER=${MYSQL_USER:-QA_1}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-QA_1_TesT}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: